FROM mcr.microsoft.com/windows/servercore:ltsc2022

SHELL ["powershell", "-Command"]
RUN Invoke-WebRequest -Uri "https://github.com/Kitware/CMake/releases/download/v3.23.2/cmake-3.23.2-windows-arm64.msi" -OutFile "cmake.msi"; \
    Start-Process msiexec.exe -ArgumentList '/i cmake.msi /quiet /norestart' -NoNewWindow -Wait; \
    Remove-Item -Force cmake.msi

WORKDIR C:\project
COPY . .

CMD ["cmd.exe"]
